---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:GYHFAE70u2c3MjQraHq-XA@db:5432/postgres
      NODE_ENV: production
  app:
    extends:
      service: common
    links:
    - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: GYHFAE70u2c3MjQraHq-XA
