---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:ia0t1dcxvr7IXhFQu6nEng@db:5432/postgres
      NODE_ENV: production
  app:
    extends:
      service: common
    links:
    - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ia0t1dcxvr7IXhFQu6nEng
